{% set name = "pipdeptree" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fe866a38113d28d527033ececc57b8e86df86b7c29edbacb33f41ee50f75b31

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pipdeptree = pipdeptree:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip

test:
  imports:
    - pipdeptree
  commands:
    - pipdeptree

about:
  home: http://github.com/naiquevin/pipdeptree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Displays installed python packages in form of a dependency tree.
  description: |
    pipdeptree is a command line utility for displaying the
    installed python packages in form of a dependency tree. It works for packages
    installed globally on a machine as well as in a virtualenv. Since pip freeze
    shows all dependencies as a flat list, finding out which are the top level
    packages and which packages do they depend on requires some effort. It can also
    be tedious to resolve conflicting dependencies because pip doesn't yet have
    true dependency resolution (more on this later). This utility tries to solve
    this problem.
  doc_url: https://github.com/naiquevin/pipdeptree
  dev_url: http://github.com/naiquevin/pipdeptree

extra:
  recipe-maintainers:
    - cdiener
