travis:
  secure:
    BINSTAR_TOKEN: CHravk6SFgPy3ZhDbH4mNvmV9NWMfG1DCnlAwcbGsn7raT9qJ00c5gfYaRBjIyKkAvIAa5uzIxssyp2zE3/YKdZeNYOTeS870zAFr5kDRg7iyIrM19k7BGHn6F4TFd27J3c6FhmymbSrIR4Lziv4qp59oaHppiAXdIwdQ8o4ozeXqkS9k0u1seQqZeTtdsjIlBjDd9wcIk7REQyTd/cHeG46WKuvlYhCb1WNCTN0DW/oTdRkBcha0ryI93o9ZttV1Ei3YTXv0TfOCa9+Y0vwLgkVlh2cS6jWKLvc1X7AE/TKNV539LqKxKoyXswhd9x3rZJJYlXQkvoF7f8OqAkGQ2f/QELF82rAXRIxC+6rctN1GEPquqaPABbc5JnQHZ1Mh6p7F8Q120PiICKpLpPG9kOCOXoSoGZ6mMvIRyrAGLFZ5txSJ9ro1/x6Pr1QbITi7c6JVnf4WL3BzSuvy1eh6jYKgMtOr98qms05Ad10pImpeAAsESm1eFTlwDgScF4822O5Dx+cre6yXhYKjQjAnRUSfBjAKB6ovdjqrDfn36df7nFQXrbVdd27VwaMCPsXYl81CyXMly78pZ7aMA9wI8U8qitc+4rYVMIBSeilFKOt4vvmLPkFnvn/H3/JTqkGnx6k2iv0xdILPboNzZ+aoD+gTKXjUsUhDfxxRWi3/E0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
